apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbitprodservice
  labels:
    app: orbitprodservice
spec:
  #replicas: 2
  selector:
    matchLabels:
      app: orbitprodservice
  template:
    metadata:
      labels:
        app: orbitprodservice
    spec:
      containers:
      - name: orbitprodservice
        image: spacexstarlink.azurecr.io/orbitprodrepo:V1.0.0.1
        ports:
        - containerPort: 8087
        resources:
          requests:
            cpu: 250m
            memory: 400Mi
          limits:
            cpu: 500m
            memory: 400Mi

---
apiVersion: v1
kind: Service
metadata:
  name: orbitprodservice
spec:
  type: LoadBalancer
  ports:
  - port: 8087
    targetPort: 8087

        

